export const SKILL_CATEGORIES = [
  {
    key: 'programming',
    skills: [
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'C#',
      'C++',
      'Go',
      'Rust',
      'Ruby',
      'PHP',
      'Swift',
      'Kotlin',
      'Scala',
      'Perl',
      'R',
      'MATLAB',
      'Dart',
      'Lua',
      'Shell/Bash',
      'SQL',
      'HTML',
      'CSS',
      'Sass',
      'GraphQL',
      'REST APIs',
      'WebSockets',
      'Assembly',
      'Objective-C',
      'Elixir',
      'Haskell',
    ],
  },
  {
    key: 'frameworks',
    skills: [
      'React',
      'Next.js',
      'Angular',
      'Vue.js',
      'Svelte',
      'Node.js',
      'Express.js',
      'Django',
      'Flask',
      'FastAPI',
      'Spring Boot',
      'Laravel',
      'Ruby on Rails',
      '.NET',
      'ASP.NET',
      'Flutter',
      'React Native',
      'Tailwind CSS',
      'Bootstrap',
      'jQuery',
      'Electron',
      'Gatsby',
      'NestJS',
      'Nuxt.js',
      'Remix',
    ],
  },
  {
    key: 'databases',
    skills: [
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'SQLite',
      'Oracle',
      'SQL Server',
      'DynamoDB',
      'Cassandra',
      'Elasticsearch',
      'Firebase',
      'Supabase',
      'Neo4j',
      'InfluxDB',
      'Snowflake',
      'BigQuery',
      'Data Modeling',
      'ETL',
      'Data Warehousing',
      'Apache Kafka',
    ],
  },
  {
    key: 'cloud',
    skills: [
      'AWS',
      'Azure',
      'GCP',
      'Docker',
      'Kubernetes',
      'Terraform',
      'Ansible',
      'Jenkins',
      'GitHub Actions',
      'GitLab CI',
      'CI/CD',
      'Linux',
      'Nginx',
      'Apache',
      'Serverless',
      'Vercel',
      'Netlify',
      'Heroku',
      'Cloudflare',
      'Monitoring/Observability',
    ],
  },
  {
    key: 'design',
    skills: [
      'Figma',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Adobe XD',
      'Sketch',
      'InVision',
      'UI Design',
      'UX Design',
      'UX Research',
      'Wireframing',
      'Prototyping',
      'Graphic Design',
      'Motion Graphics',
      'Video Editing',
      'Photography',
    ],
  },
  {
    key: 'datascience',
    skills: [
      'Machine Learning',
      'Deep Learning',
      'TensorFlow',
      'PyTorch',
      'NLP',
      'Computer Vision',
      'Data Analysis',
      'Data Visualization',
      'Pandas',
      'NumPy',
      'Scikit-learn',
      'Jupyter',
      'Power BI',
      'Tableau',
      'Statistics',
    ],
  },
  {
    key: 'projectmgmt',
    skills: [
      'Agile',
      'Scrum',
      'Kanban',
      'Jira',
      'Trello',
      'Asana',
      'Confluence',
      'Notion',
      'Waterfall',
      'Six Sigma',
      'Lean',
      'PMP',
      'PRINCE2',
      'OKRs',
      'Stakeholder Management',
    ],
  },
  {
    key: 'business',
    skills: [
      'Accounting',
      'Financial Analysis',
      'Budgeting',
      'Forecasting',
      'SAP',
      'QuickBooks',
      'Excel Advanced',
      'Financial Modeling',
      'Auditing',
      'Tax Preparation',
      'Payroll',
      'Bookkeeping',
      'Cost Analysis',
      'Risk Management',
      'Compliance',
      'Banking',
      'Investment Analysis',
      'Credit Analysis',
      'Insurance',
      'Treasury Management',
    ],
  },
  {
    key: 'marketing',
    skills: [
      'Digital Marketing',
      'SEO',
      'SEM',
      'Google Ads',
      'Facebook Ads',
      'Content Marketing',
      'Email Marketing',
      'Social Media Marketing',
      'CRM',
      'Salesforce',
      'HubSpot',
      'Market Research',
      'Brand Strategy',
      'Copywriting',
      'Public Relations',
      'Affiliate Marketing',
      'Influencer Marketing',
      'Google Analytics',
      'A/B Testing',
      'Lead Generation',
    ],
  },
  {
    key: 'hr',
    skills: [
      'Recruiting',
      'Talent Acquisition',
      'Onboarding',
      'Employee Relations',
      'Performance Management',
      'Compensation & Benefits',
      'HRIS',
      'Labor Law',
      'Organizational Development',
      'Training & Development',
    ],
  },
  {
    key: 'languages',
    skills: [
      'English',
      'Spanish',
      'Portuguese',
      'French',
      'German',
      'Mandarin',
      'Italian',
      'Japanese',
      'Korean',
      'Arabic',
    ],
  },
  {
    key: 'engineering',
    skills: [
      'AutoCAD',
      'SolidWorks',
      'CATIA',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Civil Engineering',
      'Chemical Engineering',
      'Quality Control',
      'ISO Standards',
      'Supply Chain Management',
      'Logistics',
      'Procurement',
      'Inventory Management',
      'Lean Manufacturing',
      'CNC Programming',
    ],
  },
  {
    key: 'customerservice',
    skills: [
      'Customer Support',
      'Call Center Operations',
      'Zendesk',
      'Intercom',
      'Technical Support',
      'Operations Management',
      'Process Improvement',
      'Vendor Management',
      'Facilities Management',
      'Event Planning',
    ],
  },
  {
    key: 'legal',
    skills: [
      'Contract Law',
      'Corporate Law',
      'Intellectual Property',
      'Regulatory Compliance',
      'GDPR',
      'Legal Research',
      'Litigation',
      'Mediation',
    ],
  },
  {
    key: 'healthcare',
    skills: [
      'Patient Care',
      'Electronic Health Records',
      'Medical Terminology',
      'HIPAA',
      'Clinical Research',
      'Pharmacy',
      'Nursing',
      'Public Health',
    ],
  },
] as const;

export type SkillCategory = (typeof SKILL_CATEGORIES)[number]['key'];
export type Skill = (typeof SKILL_CATEGORIES)[number]['skills'][number];

export const ALL_SKILLS = SKILL_CATEGORIES.flatMap((c) => [...c.skills]);
